### PR TITLE
Annotate command with Input in BrowserStackTask

### PR DESCRIPTION
**Pull request by nuhkoca**
Intending to fix https://github.com/browserstack/browserstack-gradle-plugin/issues/61

### CODE REVIEW

**Comment by nuhkoca** [comment]
cc @deepwired can you please have a look?

**Comment by JohnMars** [comment]
@deepwired could you please look at this PR? It's blocking us to upgrade Kotlin version

**Review by sumitra-chatterjee — APPROVED** [review]

**Review by deepwired — APPROVED** [review]
LGTM, will release by Friday if all goes well.

**Comment by nuhkoca** [comment]
Thanks @deepwired please do tests on your own as I didn't test it

**Pull request merged**
